/* Bina — fake but plausible dataset for the UI kit. Loaded as window.BINA_DATA. */
window.BINA_DATA = {
  topics: [
    { id:'agents', name:'Autonomous agents', year:2025, momentum:'rise', delta:'+312%',
      series:[4,5,6,9,12,11,18,26,34,41,52], peak:'Apr 2025', mentions:'48.2k', tier:'gold',
      blurb:'Tool-using, long-horizon systems that plan and act. The defining conversation of 2025.',
      related:['tool use','planning','memory','RLHF'] },
    { id:'reasoning', name:'Reasoning models', year:2024, momentum:'rise', delta:'+248%',
      series:[2,3,3,5,8,9,14,19,28,33,38], peak:'Dec 2024', mentions:'39.7k', tier:'',
      blurb:'Inference-time compute and chain-of-thought scaling reshaped what "bigger" means.',
      related:['chain-of-thought','test-time compute','search'] },
    { id:'diffusion', name:'Diffusion models', year:2022, momentum:'fall', delta:'−18%',
      series:[6,12,22,30,28,24,20,17,15,13,12], peak:'Aug 2023', mentions:'61.0k', tier:'',
      blurb:'Image and video generation went mainstream, then settled into steady infrastructure.',
      related:['latent space','samplers','ControlNet'] },
    { id:'rag', name:'Retrieval-augmented generation', year:2023, momentum:'fall', delta:'−9%',
      series:[3,8,16,24,27,25,23,22,20,19,18], peak:'Oct 2023', mentions:'34.5k', tier:'',
      blurb:'Grounding models in external knowledge — now a default pattern more than a frontier.',
      related:['embeddings','vector search','context windows'] },
    { id:'moe', name:'Mixture of experts', year:2024, momentum:'rise', delta:'+86%',
      series:[1,2,2,4,5,7,9,11,13,15,18], peak:'Mar 2025', mentions:'21.3k', tier:'',
      blurb:'Sparse activation made trillion-parameter models tractable to serve.',
      related:['routing','sparsity','scaling laws'] },
    { id:'alignment', name:'Alignment & safety', year:2023, momentum:'rise', delta:'+54%',
      series:[5,6,8,9,12,13,15,16,19,21,24], peak:'Feb 2025', mentions:'42.8k', tier:'',
      blurb:'From RLHF to interpretability — the field grew a conscience and a research agenda.',
      related:['interpretability','RLHF','red-teaming','evals'] },
    { id:'multimodal', name:'Multimodal models', year:2023, momentum:'rise', delta:'+131%',
      series:[2,4,6,8,11,14,18,22,27,30,35], peak:'May 2025', mentions:'37.1k', tier:'',
      blurb:'Text, image, audio and video collapsing into single unified models.',
      related:['vision','speech','any-to-any'] },
    { id:'transformers', name:'Transformers', year:2017, momentum:'fall', delta:'−4%',
      series:[1,9,20,35,48,52,49,45,42,40,38], peak:'Jun 2021', mentions:'92.6k', tier:'',
      blurb:'The architecture that started it all — now the assumed substrate beneath everything.',
      related:['attention','positional encoding','scaling'] },
  ],
  milestones: {
    agents: [
      { date:'2023-03', label:'First ReAct-style tool loops go viral' },
      { date:'2024-06', label:'Long-horizon benchmarks emerge' },
      { date:'2025-04', label:'Agent platforms hit mainstream adoption' },
    ],
    reasoning: [
      { date:'2024-09', label:'Inference-time scaling demonstrated' },
      { date:'2024-12', label:'Reasoning becomes a product category' },
    ],
  },
  years: [2017, 2020, 2022, 2023, 2024, 2025],
};
